services:
  db:
    build:
      context: .
      dockerfile: Dockerfile.pg
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-ragdb}
      POSTGRES_USER: ${POSTGRES_USER:-raguser}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-ragpass}
    ports: ["15433:5432"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-raguser} -d ${POSTGRES_DB:-ragdb}"]
      interval: 5s
      timeout: 3s
      retries: 20
    volumes:
      - dbdata:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d:ro

  dbrag:
    build:
      context: .
      dockerfile: Dockerfile.qdrant
    restart: unless-stopped
    environment:
      QDRANT__SERVICE__GRPC_PORT: ${DBRAG_QDRANT_GRPC_PORT:-6334}
      QDRANT__SERVICE__HTTP_PORT: ${DBRAG_QDRANT_HTTP_PORT:-6333}
      QDRANT__STORAGE__STORAGE_PATH: /qdrant/storage
      QDRANT__STORAGE__SNAPSHOTS_PATH: /qdrant/snapshots
      QDRANT__CLUSTER__ENABLED: ${DBRAG_QDRANT_CLUSTER_ENABLED:-false}
      QDRANT__TELEMETRY__DISABLED: ${DBRAG_QDRANT_DISABLE_TELEMETRY:-true}
    ports:
      - "16433:6333"
      - "16434:6334"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -fsS http://127.0.0.1:6333/healthz >/dev/null || exit 1",
        ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 40s
    volumes:
      - dbragdata:/qdrant/storage
      - dbragsnapshots:/qdrant/snapshots

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    environment:
      DEBUGPY: "1"
      DEBUGPY_PORT: ${DEBUGPY_PORT:-5678}
      DATABASE_URL: postgresql+psycopg://raguser:ragpass@db:5432/ragdb
      EMBEDDING_PROVIDER: ${EMBEDDING_PROVIDER:-local}
      EMBEDDING_MODEL: ${EMBEDDING_MODEL:-text-embedding-3-large}
      EMBEDDING_TARGET_DIM: ${EMBEDDING_TARGET_DIM:-1024}
      EMBEDDING_PROVIDER_BASE_URL: ${EMBEDDING_PROVIDER_BASE_URL:-https://api.openai.com/v1}
      EMBEDDING_API_KEY: ${EMBEDDING_API_KEY:-}
      LOCAL_EMBEDDING_MODEL: ${LOCAL_EMBEDDING_MODEL:-BAAI/bge-m3}
      LOCAL_EMBEDDING_BASE_URL: ${LOCAL_EMBEDDING_BASE_URL:-http://host.docker.internal:18082}
      LOCAL_EMBEDDING_URL: ${LOCAL_EMBEDDING_URL:-http://host.docker.internal:18082/embed}
      LOCAL_EMBEDDING_API_KEY: ${LOCAL_EMBEDDING_API_KEY:-}
      LOCAL_EMBEDDING_TIMEOUT_SECONDS: ${LOCAL_EMBEDDING_TIMEOUT_SECONDS:-120}
      DOCLING_VLM_MODEL: ${DOCLING_VLM_MODEL:-}
      EMBEDDING_BATCH_SIZE: ${EMBEDDING_BATCH_SIZE:-64}
      EMBEDDING_MAX_RETRIES: ${EMBEDDING_MAX_RETRIES:-5}
      EMBEDDING_BACKOFF_BASE: ${EMBEDDING_BACKOFF_BASE:-0.6}
      CHAT_PROVIDER_BASE_URL: ${CHAT_PROVIDER_BASE_URL:-https://api.openai.com/v1}
      CHAT_MODEL: ${CHAT_MODEL:-gpt-4.1}
      CHAT_TEMPERATURE: ${CHAT_TEMPERATURE:-0.2}
      CHAT_TOP_P: ${CHAT_TOP_P:-1.0}
      CHAT_MAX_TOKENS: ${CHAT_MAX_TOKENS:-2048}
      CHAT_MAX_RETRIES: ${CHAT_MAX_RETRIES:-6}
      CHAT_BACKOFF_BASE: ${CHAT_BACKOFF_BASE:-0.6}
      DEFAULT_CHAT_PROVIDER: ${DEFAULT_CHAT_PROVIDER:-openai}
      OPENAI_BASE_URL: ${OPENAI_BASE_URL:-https://api.openai.com/v1}
      OPENAI_API_KEY: ${OPENAI_API_KEY:-}
      DEEPSEEK_API_BASE: ${DEEPSEEK_API_BASE:-https://api.deepseek.com/v1}
      DEEPSEEK_API_KEY: ${DEEPSEEK_API_KEY:-no_api_key_available}
      DEEPSEEK_CHAT_MODEL: ${DEEPSEEK_CHAT_MODEL:-deepseek-chat}
      GEMINI_API_BASE: ${GEMINI_API_BASE:-https://generativelanguage.googleapis.com/v1beta}
      GEMINI_API_KEY: ${GEMINI_API_KEY:-}
      GEMINI_CHAT_MODEL: ${GEMINI_CHAT_MODEL:-gemini-1.5-pro}
      GEMINI_ENABLE_CONTEXT_CACHE: ${GEMINI_ENABLE_CONTEXT_CACHE:-true}
      GEMINI_CACHE_TTL_SECONDS: ${GEMINI_CACHE_TTL_SECONDS:-1800}
      GEMINI_CACHE_MIN_CHARS: ${GEMINI_CACHE_MIN_CHARS:-4000}
      GEMINI_MAX_TOKENS: ${GEMINI_MAX_TOKENS:-8192}
      VERTEX_PROJECT_ID: ${VERTEX_PROJECT_ID:-}
      VERTEX_LOCATION: ${VERTEX_LOCATION:-us-east1}
      VERTEX_PUBLISHER: ${VERTEX_PUBLISHER:-google}
      VERTEX_CHAT_MODEL: ${VERTEX_CHAT_MODEL:-gemini-1.5-pro-002}
      VERTEX_ENABLE_CONTEXT_CACHE: ${VERTEX_ENABLE_CONTEXT_CACHE:-true}
      VERTEX_CACHE_TTL_SECONDS: ${VERTEX_CACHE_TTL_SECONDS:-1800}
      VERTEX_CACHE_MIN_CHARS: ${VERTEX_CACHE_MIN_CHARS:-4000}
      VERTEX_CHAT_MAX_TOKENS: ${VERTEX_CHAT_MAX_TOKENS:-8192}
      VERTEX_MAX_TOKENS: ${VERTEX_MAX_TOKENS:-8192}
      VERTEX_TRUNCATE_SYSTEM_CHARS: ${VERTEX_TRUNCATE_SYSTEM_CHARS:-60000}
      VERTEX_USE_OAUTH: ${VERTEX_USE_OAUTH:-true}
      VERTEX_HTTP_TIMEOUT_SECONDS: ${VERTEX_HTTP_TIMEOUT_SECONDS:-120}
      VERTEX_ENABLE_COUNT_TOKENS: ${VERTEX_ENABLE_COUNT_TOKENS:-false}
      GROK_API_BASE: ${GROK_API_BASE:-https://api.x.ai/v1}
      GROK_API_KEY: ${GROK_API_KEY:-}
      GROK_CHAT_MODEL: ${GROK_CHAT_MODEL:-grok-3}
      GROK_MAX_TOKENS: ${GROK_MAX_TOKENS:-16384}
      GROK_CONTEXT_WINDOW: ${GROK_CONTEXT_WINDOW:-131072}
      GROK_ENABLE_CONTEXT_CACHE: ${GROK_ENABLE_CONTEXT_CACHE:-false}
      GROK_CACHE_TTL_SECONDS: ${GROK_CACHE_TTL_SECONDS:-1800}
      GROK_CACHE_MIN_CHARS: ${GROK_CACHE_MIN_CHARS:-4000}
      GOOGLE_APPLICATION_CREDENTIALS: ${GOOGLE_APPLICATION_CREDENTIALS:-}
      GCP_LOCATION: ${GCP_LOCATION:-us-central1}
      API_KEY: ${API_KEY:-replace_me}
      AUTH_TOKEN_SECRET: ${AUTH_TOKEN_SECRET:-change-me}
      AUTH_TOKEN_TTL_SECONDS: ${AUTH_TOKEN_TTL_SECONDS:-86400}
      MAX_CANDIDATE_CHUNKS: ${MAX_CANDIDATE_CHUNKS:-96}
      CHUNK_OVERLAP: ${CHUNK_OVERLAP:-240}
      MAX_CHUNK_CHARS: ${MAX_CHUNK_CHARS:-1100}
      TOP_K: ${TOP_K:-16}
      RERANK: ${RERANK:-false}
      ALLOWED_ORIGINS: ${ALLOWED_ORIGINS:-*}
      HTTP_TIMEOUT_SECONDS: ${HTTP_TIMEOUT_SECONDS:-60}
      TESS_LANGS: ${TESS_LANGS:-spa+eng}
      AUTH_USERS: ${AUTH_USERS:-username_changeme:password_changeme:role_changeme,username2_changeme:password2_changeme:role2_changeme}
      LLM_PROVIDER: ${LLM_PROVIDER:-openai}
      ENABLE_PROVIDER_FALLBACK: ${ENABLE_PROVIDER_FALLBACK:-true}
      DEEPSEEK_EMBEDDING_MODEL: ${DEEPSEEK_EMBEDDING_MODEL:-deepseek-embedder}
      ADMIN_EMAIL: ${ADMIN_EMAIL:-admin@example.com}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD:-ChangeMe_12345}
      ADMIN_FULL_NAME: ${ADMIN_FULL_NAME:-Administrator}
      DBRAG_QDRANT_URL: ${DBRAG_QDRANT_URL:-http://dbrag:6333}
      DBRAG_QDRANT_GRPC_URL: ${DBRAG_QDRANT_GRPC_URL:-}
      DBRAG_QDRANT_API_KEY: ${DBRAG_QDRANT_API_KEY:-}
      DBRAG_QDRANT_TIMEOUT_SECONDS: ${DBRAG_QDRANT_TIMEOUT_SECONDS:-120}
      RAG_DOCUMENT_ROOT: ${RAG_DOCUMENT_ROOT:-/repo/DOCS}
      RAG_ALLOWED_EXTENSIONS: ${RAG_ALLOWED_EXTENSIONS:-.pdf,.docx,.doc,.txt,.pptx,.ppt,.md}
      RAG_CHUNK_SIZE: ${RAG_CHUNK_SIZE:-1000}
      RAG_CHUNK_OVERLAP: ${RAG_CHUNK_OVERLAP:-200}
      RAG_EMBEDDING_MODEL: ${RAG_EMBEDDING_MODEL:-BAAI/bge-m3}
      RAG_EMBEDDING_DIMENSION: ${RAG_EMBEDDING_DIMENSION:-1024}
      RAG_MAX_BATCH_SIZE: ${RAG_MAX_BATCH_SIZE:-16}
      QDRANT_UPSERT_BATCH_SIZE: ${QDRANT_UPSERT_BATCH_SIZE:-128}
      NVIDIA_VISIBLE_DEVICES: ${NVIDIA_VISIBLE_DEVICES:-all}
      NVIDIA_DRIVER_CAPABILITIES: ${NVIDIA_DRIVER_CAPABILITIES:-compute,utility}
    depends_on:
      db:
        condition: service_healthy
      dbrag:
        condition: service_healthy
    ports: ["18001:8000", "15678:5678"]
    volumes:
      - ./backend/app:/app/app
      - ./backend/bin:/app/bin
      - ./backend/app/secrets/myaccount.json:/secrets/gcp.json:ro
      - ./DOCS:/repo/DOCS:ro
    gpus: ${NVIDIA_VISIBLE_DEVICES:-all}

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    environment:
      CHOKIDAR_USEPOLLING: "true"
      NEXT_WEBPACK_USEPOLLING: "true"
      WATCHPACK_POLLING: "true"
      NEXT_PUBLIC_DEFAULT_LLM: ${NEXT_PUBLIC_DEFAULT_LLM:-gpt}
      NEXT_PUBLIC_API_BASE: ${NEXT_PUBLIC_API_BASE:-http://localhost:18001}
      BACKEND_INTERNAL_URL: ${BACKEND_INTERNAL_URL:-http://backend:8000}
      NEXT_TELEMETRY_DISABLED: "1"
    depends_on:
      - backend
    ports: ["13001:3000"]
    volumes:
      - ./frontend:/usr/src/app
      - frontend_node_modules:/usr/src/app/node_modules
    command:
      [
        "sh",
        "-c",
        "npm install --no-audit --no-fund && npm run dev -- -p 3000 -H 0.0.0.0",
      ]

volumes:
  dbdata:
  dbragdata:
  dbragsnapshots:
  frontend_node_modules:
